Repository Kuadrant/kuadrant-operator, pull requests merged in 2023-05, with the labels that each got.

#176 [test] Optimizations, improvements, and unit tests for common/common.go (part 1 of 3)
  pkg/common/common.go
  pkg/common/common_test.go
Labels: target/current

#166 Istio (v1.17.2) and Gateway API (v0.6.2) version bump
  bundle/manifests/kuadrant.io_authpolicies.yaml
  bundle/manifests/kuadrant.io_kuadrants.yaml
  bundle/manifests/kuadrant.io_ratelimitpolicies.yaml
  config/crd/bases/kuadrant.io_authpolicies.yaml
  config/crd/bases/kuadrant.io_kuadrants.yaml
  config/crd/bases/kuadrant.io_ratelimitpolicies.yaml
  config/dependencies/gateway-api/kustomization.yaml
  controllers/ratelimitpolicy_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  make/istio.mk
  pkg/common/gatewayapi_utils.go
  pkg/common/gatewayapi_utils_test.go
  pkg/reconcilers/targetref_reconciler.go
  pkg/rlptools/wasm_utils_test.go
Labels: target/current, area/dependencies

#185 [fix: integration-tests] Ensure Istio gateways are ready
  controllers/ratelimitpolicy_controller_test.go
Labels: kind/bug, target/current, size/small, area/tests

#187 Optimize common package functions for improved performance
  pkg/common/common.go
  pkg/common/common_test.go
Labels: target/current

#190 [test] Unit-tests for common/k8s_utils.go (part 1 of 3)
  pkg/common/k8s_utils.go
  pkg/common/k8s_utils_test.go
Labels: target/current
