Repository Kuadrant/kuadrant-operator, pull requests merged in 2023-12, with the labels that each got.

#344 Include missing unit test
  Makefile
  controllers/authpolicy_authconfig_test.go
Labels: kind/bug, size/small, area/tests

#359 Fix authconfig annotations reconciliation
  controllers/authpolicy_authconfig.go
Labels: target/next

#364 refactor: align using CEL for target ref validation
  api/v1beta2/authpolicy_types.go
  api/v1beta2/authpolicy_types_test.go
  api/v1beta2/ratelimitpolicy_types.go
  api/v1beta2/ratelimitpolicy_types_test.go
  bundle/manifests/kuadrant.io_ratelimitpolicies.yaml
  config/crd/bases/kuadrant.io_ratelimitpolicies.yaml
  controllers/authpolicy_controller_test.go
  controllers/authpolicy_status.go
  controllers/kuadrant_status.go
  controllers/ratelimitpolicy_controller_test.go
  controllers/ratelimitpolicy_istio_wasmplugin.go
  controllers/ratelimitpolicy_status.go
  go.mod
  pkg/common/apimachinery_status_conditions.go
  pkg/common/common.go
  pkg/common/gatewayapi_utils.go
  pkg/common/gatewayapi_utils_test.go
Labels: kind/enhancement, size/small, area/api, area/dependencies

#371 fix istioctl deployment
  Makefile
  config/dependencies/istio/istio-operator.yaml
  doc/user-guides/authenticated-rl-for-app-developers.md
  doc/user-guides/authenticated-rl-with-jwt-and-k8s-authnz.md
  doc/user-guides/simple-rl-for-app-developers.md
  make/istio.mk
Labels: priority/must
