Repository Kuadrant/kuadrant-operator, pull requests merged in 2024-08, with the labels that each got.

#803 Fix release workflow
  .github/workflows/release.yaml
Labels: kind/bug

#802 Transition to Cross-Compilation for faster Docker Build Times
  .github/workflows/build-images-base.yaml
  Dockerfile
Labels: kind/enhancement, size/small

#783 fix: lower case img tags for image building
  .github/workflows/build-images-base.yaml
Labels: kind/bug, size/small
