Repository Kuadrant/kuadrant-operator, pull requests merged in 2024-11, with the labels that each got.

#944 Install sail-operator 0.1.0
  .github/workflows/test.yaml
  config/dependencies/istio/sail/deployment_patch.yaml
  config/dependencies/istio/sail/istio.yaml
  config/dependencies/istio/sail/kustomization.yaml
  doc/development.md
  hack/quickstart-setup.sh
  make/istio.mk
Labels: kind/enhancement, size/medium, area/dependencies

#976 951 finalize ratelimitpolicy v1beta3
  api/v1beta3/authpolicy_types.go
  api/v1beta3/ratelimitpolicy_types.go
  api/v1beta3/ratelimitpolicy_types_test.go
  api/v1beta3/zz_generated.deepcopy.go
  bundle/manifests/kuadrant-operator.clusterserviceversion.yaml
  bundle/manifests/kuadrant.io_ratelimitpolicies.yaml
  charts/kuadrant-operator/templates/manifests.yaml
  config/crd/bases/kuadrant.io_ratelimitpolicies.yaml
  config/samples/kuadrant_v1beta3_ratelimitpolicy.yaml
  controllers/limitador_limits_reconciler.go
  controllers/ratelimit_workflow_helpers.go
  controllers/ratelimit_workflow_test.go
  doc/rate-limiting.md
  doc/reference/ratelimitpolicy.md
  doc/user-guides/authenticated-rl-for-app-developers.md
  doc/user-guides/authenticated-rl-with-jwt-and-k8s-authnz.md
  doc/user-guides/gateway-rl-for-cluster-operators.md
  doc/user-guides/secure-protect-connect-single-multi-cluster.md
  doc/user-guides/secure-protect-connect.md
  doc/user-guides/simple-rl-for-app-developers.md
  examples/toystore/ratelimitpolicy_gateway.yaml
  examples/toystore/ratelimitpolicy_httproute.yaml
  go.mod
  go.sum
  pkg/wasm/types.go
  pkg/wasm/utils.go
  tests/common/ratelimitpolicy/ratelimitpolicy_controller_test.go
  tests/common/targetstatus/target_status_controller_test.go
  tests/envoygateway/extension_reconciler_test.go
  tests/envoygateway/rate_limit_cluster_reconciler_test.go
  tests/istio/extension_reconciler_test.go
  tests/istio/rate_limit_cluster_reconciler_test.go
Labels: kind/enhancement, size/medium, area/api, priority/must

#983 feat: tls section name support
  Makefile
  api/v1/tlspolicy_types.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/kuadrant-operator.clusterserviceversion.yaml
  bundle/manifests/kuadrant.io_authpolicies.yaml
  bundle/manifests/kuadrant.io_dnspolicies.yaml
  bundle/manifests/kuadrant.io_kuadrants.yaml
  bundle/manifests/kuadrant.io_ratelimitpolicies.yaml
  bundle/manifests/kuadrant.io_tlspolicies.yaml
  charts/kuadrant-operator/templates/manifests.yaml
  config/crd/bases/kuadrant.io_authpolicies.yaml
  config/crd/bases/kuadrant.io_dnspolicies.yaml
  config/crd/bases/kuadrant.io_kuadrants.yaml
  config/crd/bases/kuadrant.io_ratelimitpolicies.yaml
  config/crd/bases/kuadrant.io_tlspolicies.yaml
  config/dependencies/cert-manager/kustomization.yaml
  config/rbac/role.yaml
  controllers/effective_tls_policies_reconciler.go
  controllers/limitador_status_to_rlp_gateway_event_handler.go
  controllers/state_of_the_world.go
  controllers/tls_workflow.go
  controllers/tlspolicies_validator.go
  controllers/tlspolicy_status_updater.go
  controllers/tlspolicy_status_updater_test.go
  go.mod
  go.sum
  tests/common/targetstatus/target_status_controller_test.go
  tests/common/tlspolicy/tlspolicy_controller_test.go
Labels: kind/enhancement, area/api

#1001 makefile: fix incorrect PHONY for local-gatewayapi-env-setup
  make/development-environments.mk
Labels: size/small

#1000 fix: incorrect kuadrant status if limitador/authorino is not found
  controllers/kuadrant_status_updater.go
  tests/bare_k8s/kuadrant_controller_test.go
Labels: kind/bug, size/small

#1010 guides: fix missing label for AuthPolicy for guide
  doc/user-guides/auth-for-app-devs-and-platform-engineers.md
Labels: area/doc, good first issue, size/small

#1017 Case insensitive header matching and safe lookup
  pkg/wasm/utils.go
  pkg/wasm/utils_test.go
Labels: kind/bug

#1015 alignment: TargetSection print column for DNS and TLS policy
  api/v1/dnspolicy_types.go
  api/v1/tlspolicy_types.go
  bundle/manifests/kuadrant.io_dnspolicies.yaml
  bundle/manifests/kuadrant.io_tlspolicies.yaml
  charts/kuadrant-operator/templates/manifests.yaml
  config/crd/bases/kuadrant.io_dnspolicies.yaml
  config/crd/bases/kuadrant.io_tlspolicies.yaml
Labels: kind/enhancement, size/small

#1019 Remove max number of auth rules constraint
  api/v1/authpolicy_types.go
  bundle/manifests/kuadrant-operator.clusterserviceversion.yaml
  bundle/manifests/kuadrant.io_authpolicies.yaml
  charts/kuadrant-operator/templates/manifests.yaml
  config/crd/bases/kuadrant.io_authpolicies.yaml
Labels: kind/bug

#1018 fix: nil pointer for invalid path for auth
  controllers/auth_policy_status_updater.go
  controllers/authconfigs_reconciler.go
  tests/common/authpolicy/authpolicy_controller_test.go
Labels: kind/bug

#1030 Setting FailureMode from ENV
  controllers/envoy_gateway_extension_reconciler.go
  controllers/istio_extension_reconciler.go
  pkg/wasm/utils.go
  tests/envoygateway/extension_reconciler_test.go
  tests/istio/extension_reconciler_test.go
Labels: kind/enhancement

#1048 makefile: add --load flag only for podman build
  Makefile
Labels: kind/bug, size/small
