Repository Kuadrant/kuadrant-operator, pull requests merged in 2024-07, with the labels that each got.

#725 Update kind to v0.23.0
  .github/workflows/test.yaml
  Makefile
  doc/development.md
  utils/kind-cluster.yaml
Labels: kind/enhancement, size/small, dependencies

#715 fix: tlspolicy enforced condition when certificate/issuer ready condition is missing
  api/v1alpha1/dnspolicy_types.go
  api/v1alpha1/tlspolicy_types.go
  api/v1beta2/authpolicy_types.go
  api/v1beta2/ratelimitpolicy_types.go
  controllers/authpolicy_controller.go
  controllers/dnspolicy_controller.go
  controllers/helper_test.go
  controllers/ratelimitpolicy_controller.go
  controllers/suite_test.go
  controllers/test_common.go
  controllers/tlspolicy_certmanager_certificates.go
  controllers/tlspolicy_controller.go
  controllers/tlspolicy_mappers.go
  controllers/tlspolicy_mappers_test.go
  controllers/tlspolicy_status.go
  controllers/tlspolicy_status_test.go
  main.go
  pkg/library/gatewayapi/topology.go
  pkg/library/gatewayapi/types.go
  pkg/library/gatewayapi/types_test.go
  pkg/library/gatewayapi/utils.go
  pkg/library/kuadrant/test_utils.go
  pkg/library/mappers/gateway.go
  pkg/library/reconcilers/fetcher.go
  pkg/library/reconcilers/fetcher_test.go
  tests/common/dnspolicy/dnspolicy_controller_test.go
  tests/common/tlspolicy/tlspolicy_controller_test.go
Labels: kind/bug, kind/enhancement, size/medium

#756 refactor: integration tests for dns & tls policy target ref CEL validation
  api/v1alpha1/dnspolicy_types.go
  api/v1alpha1/tlspolicy_types.go
  tests/common/dnspolicy/dnspolicy_controller_test.go
  tests/common/tlspolicy/tlspolicy_controller_test.go
Labels: kind/enhancement, participation/good first issue, size/small, area/api

#727 remove cert-manager as dependency
  bundle/metadata/dependencies.yaml
  doc/install/install-openshift.md
Labels: kind/bug, size/small

#765 changed app developer dashboard to new dashboard id (#764)
  .github/workflows/upload-dashboards.yaml
  doc/observability/examples.md
Labels: kind/bug, area/doc

#608 Update limitador to 0.9.0
  api/v1beta1/kuadrant_types.go
  api/v1beta1/zz_generated.deepcopy.go
  bundle/manifests/kuadrant-operator.clusterserviceversion.yaml
  bundle/manifests/kuadrant.io_kuadrants.yaml
  config/crd/bases/kuadrant.io_kuadrants.yaml
  controllers/kuadrant_controller.go
  go.mod
  go.sum
  pkg/kuadranttools/limitador_mutators.go
  pkg/kuadranttools/limitador_mutators_test.go
  pkg/kuadranttools/limitador_tools.go
  pkg/kuadranttools/limitador_tools_test.go
  tests/common/gatewaykuadrant/gateway_kuadrant_controller_test.go
  tests/common/gatewaykuadrant/suite_test.go
  tests/common/kuadrant/kuadrant_controller_test.go
  tests/commons.go
Labels: kind/enhancement

#779 Bump go version to 1.22 🚀
  .github/workflows/build-images-base.yaml
  .github/workflows/code-style.yaml
  .github/workflows/test-alerts.yaml
  .github/workflows/test.yaml
  Dockerfile
  doc/development.md
  go.mod
Labels: kind/enhancement

#780 Update Gateway API to v1.1
  api/v1alpha1/dnspolicy_types.go
  api/v1alpha1/tlspolicy_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  api/v1beta2/authpolicy_types.go
  api/v1beta2/authpolicy_types_test.go
  api/v1beta2/ratelimitpolicy_types.go
  api/v1beta2/ratelimitpolicy_types_test.go
  api/v1beta2/zz_generated.deepcopy.go
  bundle/manifests/kuadrant-operator.clusterserviceversion.yaml
  bundle/manifests/kuadrant.io_authpolicies.yaml
  bundle/manifests/kuadrant.io_dnspolicies.yaml
  bundle/manifests/kuadrant.io_kuadrants.yaml
  bundle/manifests/kuadrant.io_ratelimitpolicies.yaml
  bundle/manifests/kuadrant.io_tlspolicies.yaml
  config/crd/bases/kuadrant.io_authpolicies.yaml
  config/crd/bases/kuadrant.io_dnspolicies.yaml
  config/crd/bases/kuadrant.io_kuadrants.yaml
  config/crd/bases/kuadrant.io_ratelimitpolicies.yaml
  config/crd/bases/kuadrant.io_tlspolicies.yaml
  config/dependencies/gateway-api/kustomization.yaml
  controllers/authpolicy_controller.go
  controllers/authpolicy_istio_authorizationpolicy.go
  controllers/dnspolicy_controller.go
  controllers/httprouteparentrefs_eventmapper.go
  controllers/ratelimitpolicy_controller.go
  controllers/target_status_controller.go
  controllers/tlspolicy_controller.go
  controllers/tlspolicy_status_test.go
  doc/reference/authpolicy.md
  doc/reference/dnspolicy.md
  doc/reference/ratelimitpolicy.md
  doc/reference/tlspolicy.md
  go.mod
  go.sum
  pkg/istio/mesh_config_test.go
  pkg/library/gatewayapi/helper_test.go
  pkg/library/gatewayapi/topology.go
  pkg/library/gatewayapi/types.go
  pkg/library/gatewayapi/types_test.go
  pkg/library/gatewayapi/utils.go
  pkg/library/kuadrant/apimachinery_status_conditions_test.go
  pkg/library/kuadrant/errors.go
  pkg/library/kuadrant/errors_test.go
  pkg/library/kuadrant/kuadrant.go
  pkg/library/kuadrant/kuadrant_test.go
  pkg/library/kuadrant/test_utils.go
  pkg/library/mappers/gateway_test.go
  pkg/library/mappers/httproute_test.go
  pkg/library/mappers/policy_to_gateway.go
  pkg/library/reconcilers/fetcher.go
  pkg/library/reconcilers/fetcher_test.go
  tests/common/authpolicy/authpolicy_controller_test.go
  tests/common/ratelimitpolicy/ratelimitpolicy_controller_test.go
  tests/common/targetstatus/target_status_controller_test.go
  tests/istio/authpolicy_controller_authorizationpolicy_test.go
  tests/istio/limitador_cluster_envoyfilter_controller_test.go
  tests/istio/rate_limiting_istio_wasmplugin_controller_test.go
Labels: kind/enhancement
