Repository Kuadrant/kuadrant-operator, pull requests merged in 2024-10, with the labels that each got.

#898 authorino version v0.18.0
  go.mod
  go.sum
Labels: kind/enhancement

#883 ADD: Watch limitador CR on cluster
  api/v1beta1/topology.go
  controllers/state_of_the_world.go
Labels: size/small

#881 ADD: Warning doc on labels
  doc/install/install-kubernetes.md
  doc/install/install-openshift.md
Labels: area/doc, size/small

#875 ratelimitpolicy v1beta3
  Makefile
  api/v1beta2/topology.go
  api/v1beta2/zz_generated.deepcopy.go
  api/v1beta3/groupversion_info.go
  api/v1beta3/ratelimitpolicy_types.go
  api/v1beta3/ratelimitpolicy_types_test.go
  api/v1beta3/topology.go
  api/v1beta3/zz_generated.deepcopy.go
  bundle/manifests/kuadrant-operator.clusterserviceversion.yaml
  bundle/manifests/kuadrant.io_ratelimitpolicies.yaml
  charts/kuadrant-operator/templates/manifests.yaml
  config/crd/bases/kuadrant.io_ratelimitpolicies.yaml
  config/manifests/bases/kuadrant-operator.clusterserviceversion.yaml
  config/samples/kuadrant_v1beta3_ratelimitpolicy.yaml
  config/samples/kustomization.yaml
  controllers/envoygateway_wasm_controller.go
  controllers/httprouteparentrefs_eventmapper.go
  controllers/limitador_cluster_envoyfilter_controller.go
  controllers/limitador_status_to_rlp_gateway_event_handler.go
  controllers/rate_limiting_istio_wasmplugin_controller.go
  controllers/ratelimitpolicy_controller.go
  controllers/ratelimitpolicy_enforced_status_controller.go
  controllers/ratelimitpolicy_limits.go
  controllers/ratelimitpolicy_status.go
  controllers/ratelimitpolicy_status_test.go
  controllers/state_of_the_world.go
  controllers/target_status_controller.go
  controllers/test_common.go
  doc/rate-limiting.md
  doc/reference/ratelimitpolicy.md
  doc/user-guides/simple-rl-for-app-developers.md
  examples/toystore/ratelimitpolicy_httproute.yaml
  main.go
  pkg/library/mappers/gateway_test.go
  pkg/library/mappers/utils_test.go
  pkg/rlptools/overrides.go
  pkg/rlptools/utils.go
  pkg/rlptools/utils_test.go
  pkg/rlptools/wasm/types.go
  pkg/rlptools/wasm/types_test.go
  pkg/rlptools/wasm/utils.go
  pkg/rlptools/wasm/utils_test.go
  tests/common/ratelimitpolicy/ratelimitpolicy_controller_test.go
  tests/common/targetstatus/target_status_controller_test.go
  tests/commons.go
  tests/envoygateway/envoygateway_limitador_cluster_controller_test.go
  tests/envoygateway/wasm_controller_test.go
  tests/istio/limitador_cluster_envoyfilter_controller_test.go
  tests/istio/rate_limiting_istio_wasmplugin_controller_test.go
Labels: kind/enhancement, size/medium, area/api

#884 consoleplugin reconciler
  .github/workflows/build-images-base.yaml
  .github/workflows/release.yaml
  Makefile
  bundle/manifests/kuadrant-operator.clusterserviceversion.yaml
  charts/kuadrant-operator/templates/manifests.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/consoleplugin_reconciler.go
  controllers/consoleplugin_reconciler_test.go
  controllers/fake/api_reader.go
  controllers/fake/event_recorder.go
  controllers/fake/manager.go
  controllers/fake/manager_builder.go
  controllers/state_of_the_world.go
  controllers/test_common.go
  controllers/topology_reconciler.go
  doc/development.md
  go.mod
  go.sum
  main.go
  make/helm.mk
  pkg/envoygateway/utils.go
  pkg/istio/utils.go
  pkg/library/gatewayapi/utils.go
  pkg/library/reconcilers/deployment.go
  pkg/library/utils/crd.go
  pkg/openshift/consoleplugin/common.go
  pkg/openshift/consoleplugin/consoleplugin.go
  pkg/openshift/consoleplugin/deployment.go
  pkg/openshift/consoleplugin/nginx_configmap.go
  pkg/openshift/consoleplugin/service.go
  pkg/openshift/utils.go
Labels: kind/enhancement, size/medium

#885 refactor: tls policy status to state of the world tasks
  controllers/state_of_the_world.go
  controllers/tls_workflow.go
  controllers/tlspolicies_validator.go
  controllers/tlspolicy_certmanager_certificates.go
  controllers/tlspolicy_controller.go
  controllers/tlspolicy_mappers.go
  controllers/tlspolicy_mappers_test.go
  controllers/tlspolicy_status.go
  controllers/tlspolicy_status_test.go
  controllers/tlspolicy_status_updater.go
  controllers/tlspolicy_status_updater_test.go
  go.sum
  pkg/library/kuadrant/apimachinery_status_conditions.go
  pkg/library/kuadrant/errors.go
  tests/common/tlspolicy/tlspolicy_controller_test.go
  tests/commons.go
Labels: kind/enhancement, size/medium

#910 Update: Improve get kuadrant resource
  controllers/authorino_reconciler.go
  controllers/limitador_reconciler.go
  controllers/state_of_the_world.go
  controllers/state_of_the_world_test.go
Labels: size/small

#888 REMOVE: kuadrant controller management of limitador
  controllers/kuadrant_controller.go
Labels: size/small

#927 refactor: effective tls policies reconciler
  controllers/effective_tls_policies_reconciler.go
  controllers/effective_tls_policies_reconciler_test.go
  controllers/state_of_the_world.go
  controllers/test_common.go
  controllers/tls_workflow.go
  controllers/tlspolicies_validator.go
  controllers/tlspolicy_certmanager.go
  controllers/tlspolicy_certmanager_certificates.go
  controllers/tlspolicy_controller.go
  controllers/tlspolicy_status_updater.go
  controllers/tlspolicy_status_updater_test.go
  main.go
  tests/common/tlspolicy/tlspolicy_controller_test.go
Labels: kind/enhancement

#924 Authpolicy/v1beta3
  Makefile
  api/v1beta2/authpolicy_types.go
  api/v1beta2/authpolicy_types_test.go
  api/v1beta2/groupversion_info.go
  api/v1beta2/route_selectors.go
  api/v1beta2/route_selectors_test.go
  api/v1beta2/topology.go
  api/v1beta2/zz_generated.deepcopy.go
  api/v1beta3/authpolicy_types.go
  api/v1beta3/authpolicy_types_test.go
  api/v1beta3/topology.go
  api/v1beta3/zz_generated.deepcopy.go
  bundle/manifests/kuadrant-operator.clusterserviceversion.yaml
  bundle/manifests/kuadrant.io_authpolicies.yaml
  charts/kuadrant-operator/templates/manifests.yaml
  config/crd/bases/kuadrant.io_authpolicies.yaml
  config/samples/kuadrant_v1beta3_authpolicy.yaml
  config/samples/kustomization.yaml
  controllers/authpolicy_authconfig.go
  controllers/authpolicy_controller.go
  controllers/authpolicy_envoysecuritypolicy_controller.go
  controllers/authpolicy_istio_authorizationpolicy_controller.go
  controllers/authpolicy_status.go
  controllers/authpolicy_status_test.go
  controllers/httprouteparentrefs_eventmapper.go
  controllers/state_of_the_world.go
  controllers/target_status_controller.go
  controllers/test_common.go
  doc/auth.md
  doc/reference/authpolicy.md
  doc/reference/route-selectors.md
  main.go
  pkg/library/mappers/httproute_test.go
  tests/common/authpolicy/authpolicy_controller_test.go
  tests/common/targetstatus/target_status_controller_test.go
  tests/commons.go
  tests/envoygateway/authpolicy_envoysecuritypolicy_controller_test.go
  tests/envoygateway/envoysecuritypolicy_referencegrant_controller_test.go
  tests/istio/authpolicy_controller_authorizationpolicy_test.go
Labels: size/large, area/api

#949 UPDATE: bump authPolicy to v1beta3 in guides
  doc/auth.md
  doc/reference/authpolicy.md
  doc/user-guides/auth-for-app-devs-and-platform-engineers.md
  doc/user-guides/authenticated-rl-for-app-developers.md
  doc/user-guides/authenticated-rl-with-jwt-and-k8s-authnz.md
  doc/user-guides/secure-protect-connect-single-multi-cluster.md
  doc/user-guides/secure-protect-connect.md
  examples/toystore/authpolicy.yaml
  examples/toystore/authpolicy_jwt-k8s-authnz.yaml
Labels: area/doc

#954 Istio installed using Sail operator added to integration tests
  .github/workflows/test.yaml
  doc/development.md
  make/istio.mk
Labels: kind/enhancement, size/small, area/dependencies
