Repository Kuadrant/kuadrant-operator, pull requests merged in 2025-02, with the labels that each got.

#1155 [ArtifactHub.io] GPG public key annotation added
  charts/kuadrant-operator/Chart.yaml
Labels: kind/enhancement

#1151 Signing Helm packages
  .github/workflows/release-helm-chart.yaml
  .gitignore
  make/helm.mk
Labels: kind/enhancement

#1161 Fix GnuPG missing directory
  .github/workflows/release-helm-chart.yaml
Labels: kind/bug

#1162 Triggering builds on full semver tags
  .github/workflows/build-images-for-tag-release.yaml
Labels: kind/bug

#1156 Add test helm upgrade path
  .github/workflows/test-upgrade.yaml
  make/helm.mk
Labels: kind/enhancement, size/medium, area/tests

#1165 Add test OLM upgrade path
  .github/workflows/test-upgrade.yaml
  Makefile
  make/catalog.mk
Labels: kind/enhancement, size/medium, area/tests

#1038 guides: auth anonymous access
  doc/user-guides/auth/anonymous-access.md
Labels: area/doc, size/medium
