Repository Kuadrant/kuadrant-operator, pull requests merged in 2025-10, with the labels that each got.

#1599 dep: go 1.24.6
  go.mod
Labels: size/small, area/dependencies, dependencies, go

#1584 DOC: dnspolicy delegation
  doc/install/multi-cluster-dns-confgiuration.md
  doc/reference/dnspolicy.md
  doc/user-guides/dns/understanding_dns_delegation.md
Labels: area/doc

#1606 UPDATE: dns dashboard
  examples/dashboards/dns-operator.json
Labels: area/doc, metrics, area/observability
